{% set name = "cmake-build-extension" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bfb5edbe2d62b3ae82c6d54a5f0bac5a3c8692d70f816386a4a022dfd18c9c3e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - cmake
    - gitpython
    - ninja
    - setuptools-scm

test:
  imports:
    - cmake_build_extension
  commands:
    - pip install --no-cache-dir --no-deps --no-build-isolation ./example
    - pytest ./example
  requires:
    - {{ compiler('cxx') }}
    - eigen
    - numpy
    - pip
    - pybind11
    - pytest
    - swig
    - python {{ python_min }}
  source_files:
    - example

about:
  home: https://github.com/diegoferigo/cmake-build-extension
  summary: Setuptools extension to build and package CMake projects.
  dev_url: https://github.com/diegoferigo/cmake-build-extension
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - diegoferigo
